name = "SyntheticLPs"
uuid = "6c18d9e4-3017-4cc6-8f05-9e4aefa327ea"
authors = ["Felix Parker <flixpar@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Dates = "1.11.0"
Distributions = "0.25"
HiGHS = "1.18.2"
JuMP = "1.0"
LinearAlgebra = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.5"
julia = "1.6"
